# Generated by Django 4.1 on 2022-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_author_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
