# Generated by Django 4.1 on 2022-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_author_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(default="This author doesn't have any description yet!", max_length=2000),
        ),
    ]
