# Generated by Django 4.1 on 2022-08-13 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='Title overall of your review', max_length=100),
            preserve_default=False,
        ),
    ]
