# Generated by Django 4.1 on 2022-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_author_description_alter_review_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
