# Generated by Django 4.1 on 2022-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(default="This author doesn't have any description yet!", max_length=3000),
        ),
    ]
